### ISSUE TITLE
EIP712 domain type

### ISSUE THREAD

**Issue by mfw78** [meetmangukiya/cow-shed#7]
## Problem

Manually defining the type is superfluous when we're importing solady which includes this.

Line reference:
https://github.com/meetmangukiya/cow-shed/blob/d67e97dd501d2fec42ab7d3e511bc3f9a2d87a8a/src/COWShed.sol#L17

## Solution

Replace with import from https://github.com/Vectorized/solady/blob/183a5c9cc3ca982492ae5fcca9e7ed6668ddb6ac/src/utils/EIP712.sol

**Comment by meetmangukiya** [comment]
cannot use it since its a contract, and if you inherit, you also inherit the caching, initializing of immutables, etc and also a public function `eip712Domain`
